site_name: Dungeoneers
theme: material
nav:
    - Home: README.md
    - 'Introduction':
        - '1-Rules Summary.md'
        - '2-Design Principles.md'
    - 'Rules':
        - '3-Making a Character.md' 
        - '4-Playing the Game.md'
        - '5-Equipment.md'
        - '6-Sorcery.md'
    - 'Tables':
        - '3e-Archetypes.md'
        - '3c-Backgrounds.md'
        - '6b-Corruption.md'        
        - '3d-Gear.md'
        - '5a-Misfires.md'
        - '3a-Names.md'
        - '4a-Scars.md'
        - '6a-Spells.md'
        - '3b-Traits.md'